### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by akvgergo** [djsall/progpar-assignm#1]
- [x] Műsörfeltöltés gomb crash ha nincs fájl kiválasztva

- [x] Fentebbihez funkcionalítás implementálása

- [x] Adatbázis diagram javítása

- [x] Dokumentáció

- [x] Kiválasztott mozi nem hozza be a filmeket
